openapi: 3.0.3
info:
  title: 'The real source is [this](https://github.com/pagopa/pn-delivery/tree/develop/docs/openapi) repository, this file is just a workaround to generate the requests and responses'
  version: 0.0.0
paths:
  # empty because we don't use them
  "/uploadS3/{key}":
    parameters:
      - $ref: "#/components/parameters/pathAwsDocumentKeyParam"
    put:
      summary: "Simulate the s3 upload"
      description: >
        This endpoint simulate the upload to s3.
      parameters:
        - $ref: "#/components/parameters/headerAmzSdkChecksumAlgParam"
        - $ref: "#/components/parameters/headerAmzMetaSecretParam"
        - $ref: "#/components/parameters/headerAmzChecksumSHA256Param"
      responses:
        '200':
          $ref: "#/components/responses/200UploadS3Response"
components:
  parameters:
    pathAwsDocumentKeyParam:
      name: key
      in: path
      description: The key of the document
      required: true
      schema:
        $ref: '#/components/schemas/AmzDocumentKey'
    headerAmzSdkChecksumAlgParam:
      name: x-amz-sdk-checksum-algorithm
      in: header
      required: false
      schema:
        $ref: '#/components/schemas/AmzSdkChecksumAlg'
    headerAmzMetaSecretParam:
      name: x-amz-meta-secret
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/AmzMetaSecret'
    headerAmzChecksumSHA256Param:
      name: x-amz-checksum-sha256
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/AmzChecksumSHA256'

  schemas:
    ApiKey:
      type: string
    AmzDocumentKey:
      example: '8F7E/9A3B/1234/AB87'
      type: string
    AmzSdkChecksumAlg:
      type: string
      enum:
        - SHA256
    AmzMetaSecret:
      type: string
    AmzChecksumSHA256:
      type: string
    AmzVersionId:
      type: integer
    NotificationRequestId:
      type: string
    PaProtocolNumber:
      type: string
    IdempotenceToken:
      type: string
    Iun:
      $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/schemas-pn-notification-v1.yaml#/components/schemas/IUN"
    PreLoadRequestBody:
      type: array
      items:
        $ref: "#/components/schemas/PreLoadRequest"
    PreLoadRequest:
      $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/api-external-b2b-pa-v1.yaml#/components/schemas/PreLoadRequest"
    PreLoadResponseBody:
      type: array
      items:
        $ref: "#/components/schemas/PreLoadResponse"
    PreLoadResponse:
      $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/api-external-b2b-pa-v1.yaml#/components/schemas/PreLoadResponse"
    NewNotificationRequest:
      description: I campi utilizzati per la creazione di una nuova Notifica.
      type: object
      required:
        - paProtocolNumber
        - subject
        - recipients
        - documents
        - physicalCommunicationType
        - notificationFeePolicy
      properties:
        idempotenceToken:
          description: >-
            Identificativo utilizzabile dal chiamante per disambiguare differenti
            "richieste di notificazione" effetuate con lo stesso numero di protocollo
            (campo _paProtocolNumber_). Questo può essere necessario in caso di
            "richiesta di notifica" rifiutata per errori nei codici di verifica degli
            allegati.
          type: string
        paProtocolNumber:
          description: >-
            Numero di protocollo che la PA mittente assegna alla notifica stessa
          type: string
        subject:
          type: string
          description: titolo della notifica
        abstract:
          type: string
          description: descrizione sintetica della notifica
        recipients:
          type: array
          description: Informazioni sui destinatari
          items:
            $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/schemas-pn-notification-v1.yaml#/components/schemas/NotificationRecipient"
        documents:
          type: array
          description: Documenti notificati
          items:
            # $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/schemas-pn-notification-v1.yaml#/components/schemas/NotificationDocument"
            $ref: "#/components/schemas/NotificationDocument"
        notificationFeePolicy:
          type: string
          description: >-
            Politica di addebitamento dei costi di notifica. <br/>
            - _FLAT_RATE_: costo forfettario fisso. <br/>
            - _DELIVERY_MODE_: costo calcolato in base all'effettivo percorso di notifica. <br/>
          enum:
            - FLAT_RATE
            - DELIVERY_MODE
        cancelledIun:
          type: string
          description: IUN della notifica annullata da questa notifica
        physicalCommunicationType:
          type: string
          description: Tipologia comunicazione fisica
          enum:
            - SIMPLE_REGISTERED_LETTER
            - REGISTERED_LETTER_890
        senderDenomination:
          description: Denominazione dell'ente mittente
          type: string
        senderTaxId:
          description: Codice Fiscale dell'ente mittente
          type: string
        group:
          type: string
          description: Gruppo di utenti dell'ente mittente che può visualizzare la notifica
        amount:
          type: integer
          description: Importo della notifica in eurocent
        paymentExpirationDate:
          type: string
          pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])$"
          description: Data di scadenza del pagamento nel formato YYYY-MM-DD riferito all'Italia
          # gestito come stringa e pattern perchè con format: date open-api-generator non lo gestiva correttamente
    NewNotificationResponse:
      $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/api-external-b2b-pa-v1.yaml#/components/schemas/NewNotificationResponse"
    Problem:
      $ref: "https://raw.githubusercontent.com/pagopa/validator-pn-delivery/a0bb195953fd0b8a01d50b029991df4e903720b7/docs/openapi/schemas-pn-errors-v1.yaml#/components/schemas/Problem"
    ProblemError:
      $ref: "https://raw.githubusercontent.com/pagopa/validator-pn-delivery/a0bb195953fd0b8a01d50b029991df4e903720b7/docs/openapi/schemas-pn-errors-v1.yaml#/components/schemas/ProblemError"
    NotificationDocument:
      description: >-
        Un documento da notifcare
      type: object
      allOf:
        - $ref: "#/components/schemas/NotificationAttachment"
        - type: object
          properties:
            title:
              type: string
              description: Titolo del documento allegato
            requiresAck:
              type: boolean
              description: >-
                Se presente e valorizzato __true__ il download del documento
                diventa necessario al fine del perfezionamento per presa visione.
            sendByMail:
              type: boolean
              description: >-
                Se presente e valorizzato __true__ il documento verrà spedito
                nelle comunicazioni cartacee. In MVP questo flag sarà attivabile
                solo su un documento.
            docIdx:
              type: string
              description: >-
                Indice del documento partendo da 0.
    NotificationAttachment:
      description: >-
        Un allegato della notifica.
      type: object
      required:
        - digests
        - contentType
        - ref
      properties:
        digests:
          $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/schemas-pn-notification-v1.yaml#/components/schemas/NotificationAttachmentDigests"
        contentType:
          type: string
          description: tipo di contenuto dell'allegato, supportato application/pdf
        ref:
          $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/schemas-pn-notification-v1.yaml#/components/schemas/NotificationAttachmentBodyRef"
    NewNotificationRequestStatusResponse:
      allOf:
        - $ref: "#/components/schemas/NewNotificationRequest"
        - type: object
          required:
            - notificationRequestId
            - notificationRequestStatus
          properties:
            notificationRequestId:
              description: >-
                identificativo univoco di una richiesta di invio notifica, non è lo IUN
              type: string
            notificationRequestStatus:
              description: >-
                - __WAITING__: in attesa di essere valutata
                - __ACCEPTED__: richiesta di notifica accettata, lo IUN è valorizzato
                - __REFUSED__: richiesta di notifica rifiutata, è valorizzato il campo _errors_
              type: string
            retryAfter:
              type: number
              description: >-
                Numero di secondi da attendere prima di effettuare una nuova richiesta per
                la stessa entità; valorizzato quando lo status è __WAITING__.
            iun:
              $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery/0599f1287a08c315bc20410fc57a666e0fa6f79d/docs/openapi/schemas-pn-notification-v1.yaml#/components/schemas/IUN"
            errors:
              description: >-
                Elenco degli errori che hanno causato il rifiuto della richiesta di notifica
              type: array
              items:
                $ref: '#/components/schemas/ProblemError'
    FullSentNotification:
      description: >-
        Le informazioni riguardanti una notifica (richiesta di notifica accettata) e il 
        processo di inoltro della notifica verso il cittadino.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/pagopa/pn-delivery/develop/docs/openapi/schemas-pn-notification-v1.yaml#/components/schemas/SentNotification'
        - type: object
          required:
            - notificationStatus
            - notificationStatusHistory
            - timeline
          properties:
            notificationStatus:
              $ref: '#/components/schemas/NotificationStatus'
            notificationStatusHistory:
              $ref: '#/components/schemas/NotificationStatusHistory'
            timeline:
              description: >-
                elenco dettagliato di tutto ciò che è accaduto durrante il processo di notifica
              type: array
              items:
                $ref: '#/components/schemas/TimelineElement'
    TimelineElement:
      type: object
      additionalProperties: false
      properties:
        elementId:
          type: string
          description: >-
            Identificativo dell'elemento di timeline: insieme allo IUN della notifica definisce in 
            maniera univoca l'elemento di timeline
        timestamp:
          type: string
          description: Momento in cui avviene l'evento desritto in questo elemento
            di timeline
          format: date-time
        legalFactsIds:
          type: array
          items:
            $ref: "#/components/schemas/LegalFactsId"
          description: >-
            Chiavi dei documenti che provano l'effettivo accadimento dell'evento descritto in timeline.
            Questo elemento
        category:
          $ref: '#/components/schemas/TimelineElementCategory'
        details:
          $ref: '#/components/schemas/TimelineElementDetails'
    LegalFactsId:
      description: Chiavi dei documenti generati durante il processo di consegna cartacea
      type: object
      required:
        - key
        - category
      properties:
        key:
          description: >-
            Chiave dell'atto opponibile a terzi generato durante il processo di consegna
          type: string
        category:
          $ref: '#/components/schemas/LegalFactCategory'
    LegalFactCategory:
      title: Tipi di atti opponibili a terzi
      description: >-
        Tipi di atti opponibili a terzi che Piattaforam Notiiche mette a disposizione dei suoi utenti.
          - _SENDER_ACK_: atto di "presa in carico" di una notifica
          - _DIGITAL_DELIVERY_: ...
      type: string
      enum:
        - SENDER_ACK
        - DIGITAL_DELIVERY
        - ANALOG_DELIVERY
        - RECIPIENT_ACCESS
    TimelineElementCategory:
      type: string
      enum:
        - REQUEST_ACCEPTED
        - SEND_COURTESY_MESSAGE
        - GET_ADDRESS
        - PUBLIC_REGISTRY_CALL
        - PUBLIC_REGISTRY_RESPONSE
        - SCHEDULE_ANALOG_WORKFLOW
        - SCHEDULE_DIGITAL_WORKFLOW
        - SEND_DIGITAL_DOMICILE
        - SEND_DIGITAL_DOMICILE_FEEDBACK
        - SEND_DIGITAL_FEEDBACK
        - REFINEMENT
        - SCHEDULE_REFINEMENT
        - DIGITAL_SUCCESS_WORKFLOW
        - DIGITAL_FAILURE_WORKFLOW
        - ANALOG_SUCCESS_WORKFLOW
        - ANALOG_FAILURE_WORKFLOW
        - SEND_SIMPLE_REGISTERED_LETTER
        - NOTIFICATION_VIEWED
        - SEND_ANALOG_DOMICILE
        - SEND_PAPER_FEEDBACK
        - PAYMENT
        - COMPLETELY_UNREACHABLE
        - REQUEST_REFUSED
        - AAR_GENERATION
        - NOT_HANDLED
    TimelineElementDetails:
      description: The raw event payload that will be different based on the event.
      oneOf:
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/NotificationRequestAcceptedDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/AnalogFailureWorkflowDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/AnalogSuccessWorkflowDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/CompletelyUnreachableDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/DigitalFailureWorkflowDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/DigitalSuccessWorkflowDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/GetAddressInfoDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/NotificationViewedDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/PublicRegistryCallDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/PublicRegistryResponseDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/RefinementDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/RequestRefusedDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/ScheduleAnalogWorkflowDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/ScheduleDigitalWorkflowDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/ScheduleRefinementDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/SendCourtesyMessageDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/SendDigitalDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/SendDigitalFeedbackDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/SendAnalogDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/SendAnalogFeedbackDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/SimpleRegisteredLetterDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/AarGenerationDetails"
        - "$ref": "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/NotHandledDetails"
    NotificationStatus:
      $ref: 'https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-status-v1.yaml#/components/schemas/NotificationStatus'
    NotificationStatusHistory:
      description: elenco degli avanzamenti effettuati dal processo di notifica
      type: array
      items:
        $ref: "#/components/schemas/NotificationStatusHistoryElement"
    NotificationStatusHistoryElement:
      description: elenco degli avanzamenti effettuati dal processo di notifica
      type: object
      required:
        - status
        - activeFrom
        - relatedTimelineElements
      properties:
        status:
          $ref: "#/components/schemas/NotificationStatus"
        activeFrom:
          type: string
          description: data e ora di raggiungimento dello stato di avanzamento
          format: date-time
        relatedTimelineElements:
          type: array
          description: Eventi avvenuti nello stato
          items:
            $ref: "https://raw.githubusercontent.com/pagopa/pn-delivery-push/c8b449ac03503aa67e0bbd699c416b6c8266aeea/docs/openapi/schemas-pn-timeline-v1.yaml#/components/schemas/TimelineElementId"

  responses:
    200UploadS3Response:
      description: >
        The upload to s3 response
      headers:
        x-amz-version-id:
          schema:
          $ref: "#/components/schemas/AmzVersionId"
