import crypto from 'crypto';
import * as E from 'fp-ts/Either';
import * as TE from 'fp-ts/TaskEither';
import * as RA from 'fp-ts/ReadonlyArray';
import * as O from 'fp-ts/Option';
import { flow, pipe } from 'fp-ts/function';
import { NewNotificationRepository } from '../domain/NewNotificationRepository';
import { CheckNotificationStatusRecordRepository } from '../domain/CheckNotificationStatusRepository';
import { ConsumeEventStreamRecordRepository } from '../domain/ConsumeEventStreamRecordRepository';
import {
  GetPaymentNotificationMetadataRecord,
  GetPaymentNotificationMetadataRecordRepository,
  makePaymentNotificationAttachmentDownloadMetadataResponse,
} from '../domain/GetPaymentNotificationMetadataRecordRepository';
import { ApiKey } from '../generated/definitions/ApiKey';
import { Iun } from '../generated/definitions/Iun';
import { authorizeApiKey } from '../domain/authorize';
import { computeSnapshot } from '../domain/Snapshot';
import { Notification } from '../domain/Notification';
import { NotificationPaymentAttachment } from '../generated/definitions/NotificationPaymentAttachment';
import { NotificationPaymentInfo } from '../generated/definitions/NotificationPaymentInfo';

// FIXME: The attachmentName type should be an enum -> check type generated by openapi
const getNotificationPaymentAttachment =
  (attachmentName: string) =>
  (payment: NotificationPaymentInfo): O.Option<NotificationPaymentAttachment> => {
    switch (attachmentName) {
      case 'F24_FLAT':
        return O.fromNullable(payment.f24flatRate);
      case 'F24_STANDARD':
        return O.fromNullable(payment.f24standard);
      case 'PAGOPA':
        return O.fromNullable(payment.pagoPaForm);
      default:
        return O.none;
    }
  };

const getRecipientPayment = (recipients: Notification['recipients']): ReadonlyArray<NotificationPaymentInfo> =>
  pipe(
    recipients,
    RA.map((recipient) => O.fromNullable(recipient.payment)),
    RA.compact
  );

export const GetPaymentNotificationMetadataUseCase =
  (
    occurrencesAfterComplete: number,
    senderPAId: string,
    createNotificationRequestRecordRepository: NewNotificationRepository,
    findNotificationRequestRecordRepository: CheckNotificationStatusRecordRepository,
    consumeEventStreamRecordRepository: ConsumeEventStreamRecordRepository,
    getPaymentNotificationMetadataRepository: GetPaymentNotificationMetadataRecordRepository,
    iunGenerator: () => string = crypto.randomUUID,
    dateGenerator: () => Date = () => new Date()
  ) =>
  (apiKey: ApiKey) =>
  (iun: Iun) =>
  (recipientId: number) =>
  (attachmentName: string): TE.TaskEither<Error, GetPaymentNotificationMetadataRecord['output']> =>
    pipe(
      authorizeApiKey(apiKey),
      E.map(() =>
        pipe(
          TE.of(computeSnapshot(occurrencesAfterComplete, senderPAId, iunGenerator, dateGenerator)),
          TE.ap(createNotificationRequestRecordRepository.list()),
          TE.ap(findNotificationRequestRecordRepository.list()),
          TE.ap(consumeEventStreamRecordRepository.list()),
          TE.map(
            flow(
              RA.filterMap(O.fromEither),
              RA.chain((notification) => (notification.iun === iun ? notification.recipients : RA.empty)),
              getRecipientPayment,
              RA.findLastMap(getNotificationPaymentAttachment(attachmentName)),
              O.map(makePaymentNotificationAttachmentDownloadMetadataResponse),
              O.map((paymentAttachment) => ({ statusCode: 200 as const, returned: paymentAttachment })),
              O.getOrElseW(() => ({ statusCode: 404 as const, returned: undefined }))
            )
          )
        )
      ),
      flow(E.sequence(TE.ApplicativePar), TE.map(E.toUnion)),
      TE.map((output) => ({
        type: 'GetPaymentNotificationMetadataRecord' as const,
        input: { apiKey, iun, recipientId, attachmentName },
        output,
      })),
      TE.chain(getPaymentNotificationMetadataRepository.insert),
      TE.map((record) => record.output)
    );

export type GetPaymentNotificationMetadataUseCase = ReturnType<typeof GetPaymentNotificationMetadataUseCase>;
