name: Build container image and push it to the container registry, according to the value of the push parameter
on:
  workflow_call:
    inputs:
      registry:
        description: 'The container registry to use. Default: ghcr.io'
        type: string
        required: false
        default: 'ghcr.io'
      image_name:
        description: 'The name of the container image.'
        type: string
        required: true
      push:
        description: 'If true, push the container image to the container registry. Default: false'
        type: boolean
        required: false
        default: false
    outputs:
      full_image_name:
        description: 'The full container image name, containing the registry, the image name and the version.'
        value: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ jobs.build_push_image.steps.meta.outputs.version }}
    secrets:
      token:
        description: 'The token to use for authentication against the container registry.'
        required: true

jobs:
  build_push_image:
    name: Build container image and push it to the container registry (if push parameter is true)
    runs-on: ubuntu-latest

    # Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}

      # https://github.com/docker/build-push-action
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}

