name: Create and publish a container image

on:
  push:
    tags:
      # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
      - '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'

jobs:
  build_image:
    name: Build the container image
    uses: pagopa/pn-local-emulator/.github/workflows/build_push_image.yaml@features/cd-docker-image
    with:
      image_name: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  vulnerabilities_scan:
    name: Scan for vulnerabilities
    needs:
      - build_image
    uses: pagopa/pn-local-emulator/.github/workflows/trivy.yaml@features/cd-docker-image
    with:
      container_image_name: ${{ needs.build_image.outputs.full_image_name }}

  push_image:
    name: Push the container image to the container registry
    needs:
      - vulnerabilities_scan
    uses: pagopa/pn-local-emulator/.github/workflows/build_push_image.yaml@features/cd-docker-image
    with:
      image_name: ${{ github.repository }}
      push: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
