name: Create and publish a container image

on:
  push:
    tags:
      - '*'

jobs:
  build_image:
    name: Build the container image
    uses: ./.github/workflows/build_push_image.yaml
    with:
      image_name: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  vulnerabilities_scan:
    name: Scan for vulnerabilities
    needs:
      - build_image
    uses: ./.github/workflows/trivy.yaml
    with:
      container_image_name: ${{ needs.build_image.outputs.full_image_name }}

  push_image:
    name: Push the container image to the container registry
    needs:
      - vulnerabilities_scan
    uses: ./.github/workflows/build_push_image.yaml
    with:
      image_name: ${{ github.repository }}
      push: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
