name: CI

on: pull_request

jobs:
  build:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm ci

      - name: Generate code
        run: npm run generate

      - name: Compile
        run: npm run compile

      - name: Lint code
        run: npm run lint

      - name: Execute tests
        run: npm test

  build_image:
    name: Build the container image
    needs:
      - build
    uses: ./.github/workflows/actions/build_push_image.yaml
    with:
      image_name: ${{ github.repository }}
      push: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
